spring:
    datasource:
        url: jdbc:mariadb://bitcamp190705.cqlznyk14le0.ap-northeast-2.rds.amazonaws.com:3306/bitcamp190705
        driverClassName: org.mariadb.jdbc.Driver
        username: bitcamp190705
        password: bitcamp190705
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
    port: 9000
logging:
  level:
    org.springframework.security: debug 
